library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- Minimal transmit-only Ethernet/IPv4/UDP MAC used by the board demo.
--
-- UDP_VALID/UDP_READY use a standard valid-ready handshake. UDP_PAYLOAD is
-- latched on a rising clock edge where both are high, and its most-significant
-- byte is transmitted first. IPv4/UDP lengths and checksums, minimum Ethernet
-- padding, and the Ethernet FCS are generated by this entity.
entity udp_to_gmii is
    generic (
        UDP_PAYLOAD_BYTE_COUNT   : positive range 1 to 1472 := 26;
        SOURCE_MAC_ADDRESS       : std_logic_vector(47 downto 0) := x"020000000001";
        DESTINATION_MAC_ADDRESS  : std_logic_vector(47 downto 0) := x"FFFFFFFFFFFF";
        SOURCE_IP_ADDRESS        : std_logic_vector(31 downto 0) := x"01020364";
        DESTINATION_IP_ADDRESS   : std_logic_vector(31 downto 0) := x"01020304";
        SOURCE_UDP_PORT          : natural range 0 to 65535 := 1234;
        DESTINATION_UDP_PORT     : natural range 0 to 65535 := 5678
    );
    port (
        clk         : in  std_logic;
        rst         : in  std_logic;
        clk_enable  : in  std_logic;
        udp_valid   : in  std_logic;
        udp_payload : in  std_logic_vector(
            UDP_PAYLOAD_BYTE_COUNT * 8 - 1 downto 0);
        udp_ready   : out std_logic;
        frame_sent  : out std_logic;
        gmii_tx_en  : out std_logic;
        gmii_txd    : out std_logic_vector(7 downto 0);
        gmii_tx_er  : out std_logic
    );
end entity udp_to_gmii;

architecture rtl of udp_to_gmii is
    constant ETHERNET_HEADER_BYTES : positive := 14;
    constant IPV4_HEADER_BYTES     : positive := 20;
    constant UDP_HEADER_BYTES      : positive := 8;
    constant DESTINATION_MAC_OFFSET : natural := 0;
    constant SOURCE_MAC_OFFSET      : natural := 6;
    constant ETHERTYPE_OFFSET       : natural := 12;
    constant IPV4_OFFSET            : natural := ETHERNET_HEADER_BYTES;
    constant UDP_OFFSET             : natural :=
        ETHERNET_HEADER_BYTES + IPV4_HEADER_BYTES;
    constant PROTOCOL_HEADER_BYTES : positive :=
        ETHERNET_HEADER_BYTES + IPV4_HEADER_BYTES + UDP_HEADER_BYTES;
    constant MIN_FRAME_DATA_BYTES  : positive := 60;

    constant UDP_LENGTH     : positive :=
        UDP_HEADER_BYTES + UDP_PAYLOAD_BYTE_COUNT;
    constant IP_TOTAL_LENGTH : positive :=
        IPV4_HEADER_BYTES + UDP_LENGTH;
    constant UNPADDED_FRAME_DATA_BYTES : positive :=
        PROTOCOL_HEADER_BYTES + UDP_PAYLOAD_BYTE_COUNT;
    constant PAYLOAD_WORD_COUNT : positive :=
        (UDP_PAYLOAD_BYTE_COUNT + 1) / 2;

    function calculate_padding_byte_count(
        frame_data_bytes : natural
    ) return natural is
    begin
        if frame_data_bytes < MIN_FRAME_DATA_BYTES then
            return MIN_FRAME_DATA_BYTES - frame_data_bytes;
        end if;
        return 0;
    end function;

    constant PADDING_BYTE_COUNT : natural :=
        calculate_padding_byte_count(UNPADDED_FRAME_DATA_BYTES);

    function last_index_or_zero(count_value : natural) return natural is
    begin
        if count_value = 0 then
            return 0;
        end if;
        return count_value - 1;
    end function;

    constant PADDING_LAST_INDEX : natural :=
        last_index_or_zero(PADDING_BYTE_COUNT);

    function checksum_add (
        sum_value  : unsigned(15 downto 0);
        word_value : unsigned(15 downto 0)
    ) return unsigned is
        variable extended_sum : unsigned(16 downto 0);
    begin
        extended_sum := ('0' & sum_value) + ('0' & word_value);
        if extended_sum(16) = '1' then
            extended_sum := ('0' & extended_sum(15 downto 0)) + 1;
        end if;
        return extended_sum(15 downto 0);
    end function;

    function finish_udp_checksum (
        sum_value : unsigned(15 downto 0)
    ) return std_logic_vector is
        variable result : unsigned(15 downto 0);
    begin
        result := not sum_value;
        -- In IPv4, zero means that the UDP checksum is disabled.
        if result = 0 then
            result := (others => '1');
        end if;
        return std_logic_vector(result);
    end function;

    function crc32_next (
        crc_value  : std_logic_vector(31 downto 0);
        data_value : std_logic_vector(7 downto 0)
    ) return std_logic_vector is
        variable result : std_logic_vector(31 downto 0) := crc_value;
    begin
        for bit_index in 0 to 7 loop
            if (result(0) xor data_value(bit_index)) = '1' then
                result := ('0' & result(31 downto 1)) xor x"EDB88320";
            else
                result := '0' & result(31 downto 1);
            end if;
        end loop;
        return result;
    end function;

    function make_ipv4_checksum return std_logic_vector is
        variable sum_value : unsigned(15 downto 0) := (others => '0');
    begin
        sum_value := checksum_add(sum_value, x"4500");
        sum_value := checksum_add(sum_value, to_unsigned(IP_TOTAL_LENGTH, 16));
        sum_value := checksum_add(sum_value, x"0001");
        sum_value := checksum_add(sum_value, x"0000");
        sum_value := checksum_add(sum_value, x"4011");
        sum_value := checksum_add(
            sum_value, unsigned(SOURCE_IP_ADDRESS(31 downto 16)));
        sum_value := checksum_add(
            sum_value, unsigned(SOURCE_IP_ADDRESS(15 downto 0)));
        sum_value := checksum_add(
            sum_value, unsigned(DESTINATION_IP_ADDRESS(31 downto 16)));
        sum_value := checksum_add(
            sum_value, unsigned(DESTINATION_IP_ADDRESS(15 downto 0)));
        return std_logic_vector(not sum_value);
    end function;

    function make_udp_initial_sum return unsigned is
        variable sum_value : unsigned(15 downto 0) := (others => '0');
    begin
        sum_value := checksum_add(
            sum_value, unsigned(SOURCE_IP_ADDRESS(31 downto 16)));
        sum_value := checksum_add(
            sum_value, unsigned(SOURCE_IP_ADDRESS(15 downto 0)));
        sum_value := checksum_add(
            sum_value, unsigned(DESTINATION_IP_ADDRESS(31 downto 16)));
        sum_value := checksum_add(
            sum_value, unsigned(DESTINATION_IP_ADDRESS(15 downto 0)));
        sum_value := checksum_add(sum_value, x"0011");
        sum_value := checksum_add(sum_value, to_unsigned(UDP_LENGTH, 16));
        sum_value := checksum_add(sum_value, to_unsigned(SOURCE_UDP_PORT, 16));
        sum_value := checksum_add(
            sum_value, to_unsigned(DESTINATION_UDP_PORT, 16));
        sum_value := checksum_add(sum_value, to_unsigned(UDP_LENGTH, 16));
        return sum_value;
    end function;

    constant IP_TOTAL_LENGTH_WORD : std_logic_vector(15 downto 0) :=
        std_logic_vector(to_unsigned(IP_TOTAL_LENGTH, 16));
    constant UDP_LENGTH_WORD          : std_logic_vector(15 downto 0) :=
        std_logic_vector(to_unsigned(UDP_LENGTH, 16));
    constant SOURCE_UDP_PORT_WORD      : std_logic_vector(15 downto 0) :=
        std_logic_vector(to_unsigned(SOURCE_UDP_PORT, 16));
    constant DESTINATION_UDP_PORT_WORD : std_logic_vector(15 downto 0) :=
        std_logic_vector(to_unsigned(DESTINATION_UDP_PORT, 16));
    constant IPV4_HEADER_CHECKSUM : std_logic_vector(15 downto 0) :=
        make_ipv4_checksum;
    constant UDP_INITIAL_SUM     : unsigned(15 downto 0) :=
        make_udp_initial_sum;

    function header_byte (
        byte_index         : natural;
        udp_checksum_value : std_logic_vector(15 downto 0)
    ) return std_logic_vector is
        variable result : std_logic_vector(7 downto 0) := x"00";
    begin
        case byte_index is
            when DESTINATION_MAC_OFFSET to SOURCE_MAC_OFFSET - 1 =>
                result := DESTINATION_MAC_ADDRESS(
                    47 - byte_index * 8 downto 40 - byte_index * 8);
            when SOURCE_MAC_OFFSET to ETHERTYPE_OFFSET - 1 =>
                result := SOURCE_MAC_ADDRESS(
                    47 - (byte_index - SOURCE_MAC_OFFSET) * 8 downto
                    40 - (byte_index - SOURCE_MAC_OFFSET) * 8);
            when ETHERTYPE_OFFSET => result := x"08";
            when ETHERTYPE_OFFSET + 1 => result := x"00";
            when IPV4_OFFSET => result := x"45";
            when IPV4_OFFSET + 1 => result := x"00";
            when IPV4_OFFSET + 2 =>
                result := IP_TOTAL_LENGTH_WORD(15 downto 8);
            when IPV4_OFFSET + 3 =>
                result := IP_TOTAL_LENGTH_WORD(7 downto 0);
            when IPV4_OFFSET + 4 => result := x"00";
            when IPV4_OFFSET + 5 => result := x"01";
            when IPV4_OFFSET + 6 => result := x"00";
            when IPV4_OFFSET + 7 => result := x"00";
            when IPV4_OFFSET + 8 => result := x"40";
            when IPV4_OFFSET + 9 => result := x"11";
            when IPV4_OFFSET + 10 =>
                result := IPV4_HEADER_CHECKSUM(15 downto 8);
            when IPV4_OFFSET + 11 =>
                result := IPV4_HEADER_CHECKSUM(7 downto 0);
            when IPV4_OFFSET + 12 to IPV4_OFFSET + 15 =>
                result := SOURCE_IP_ADDRESS(
                    31 - (byte_index - IPV4_OFFSET - 12) * 8 downto
                    24 - (byte_index - IPV4_OFFSET - 12) * 8);
            when IPV4_OFFSET + 16 to IPV4_OFFSET + 19 =>
                result := DESTINATION_IP_ADDRESS(
                    31 - (byte_index - IPV4_OFFSET - 16) * 8 downto
                    24 - (byte_index - IPV4_OFFSET - 16) * 8);
            when UDP_OFFSET =>
                result := SOURCE_UDP_PORT_WORD(15 downto 8);
            when UDP_OFFSET + 1 =>
                result := SOURCE_UDP_PORT_WORD(7 downto 0);
            when UDP_OFFSET + 2 =>
                result := DESTINATION_UDP_PORT_WORD(15 downto 8);
            when UDP_OFFSET + 3 =>
                result := DESTINATION_UDP_PORT_WORD(7 downto 0);
            when UDP_OFFSET + 4 =>
                result := UDP_LENGTH_WORD(15 downto 8);
            when UDP_OFFSET + 5 =>
                result := UDP_LENGTH_WORD(7 downto 0);
            when UDP_OFFSET + 6 =>
                result := udp_checksum_value(15 downto 8);
            when UDP_OFFSET + 7 =>
                result := udp_checksum_value(7 downto 0);
            when others => null;
        end case;
        return result;
    end function;

    type tx_state_t is (
        IDLE,
        CHECKSUM_PAYLOAD,
        PREAMBLE,
        SFD,
        HEADER,
        PAYLOAD,
        PADDING,
        FCS,
        INTER_FRAME_GAP
    );
    signal state : tx_state_t := IDLE;

    signal checksum_word_counter : natural range 0 to PAYLOAD_WORD_COUNT - 1 := 0;
    signal preamble_counter      : natural range 0 to 6 := 0;
    signal header_counter        : natural range 0 to PROTOCOL_HEADER_BYTES - 1 := 0;
    signal payload_counter       : natural range 0 to UDP_PAYLOAD_BYTE_COUNT - 1 := 0;
    signal padding_counter       : natural range 0 to MIN_FRAME_DATA_BYTES - 1 := 0;
    signal fcs_counter           : natural range 0 to 3 := 0;
    signal ifg_counter           : natural range 0 to 11 := 0;

    signal payload_latched : std_logic_vector(udp_payload'range) :=
        (others => '0');
    signal udp_sum      : unsigned(15 downto 0) := (others => '0');
    signal udp_checksum : std_logic_vector(15 downto 0) := (others => '0');
    signal frame_crc    : std_logic_vector(31 downto 0) := (others => '1');
    signal udp_ready_i  : std_logic;
begin
    assert IP_TOTAL_LENGTH <= 1500
        report "UDP payload exceeds the standard 1500-byte Ethernet MTU"
        severity failure;

    udp_ready_i <= '1' when state = IDLE and rst = '0' else '0';
    udp_ready   <= udp_ready_i;
    gmii_tx_er <= '0';

    transmit : process(clk)
        variable next_sum     : unsigned(15 downto 0);
        variable data_value   : std_logic_vector(7 downto 0);
        variable fcs_value    : std_logic_vector(31 downto 0);
        variable has_low_byte : boolean;
        variable payload_word : unsigned(15 downto 0);
        variable payload_high : natural;
    begin
        if rising_edge(clk) then
            frame_sent <= '0';

            if rst = '1' then
                state                     <= IDLE;
                checksum_word_counter     <= 0;
                preamble_counter          <= 0;
                header_counter            <= 0;
                payload_counter           <= 0;
                padding_counter           <= 0;
                fcs_counter               <= 0;
                ifg_counter               <= 0;
                payload_latched           <= (others => '0');
                udp_sum                   <= (others => '0');
                udp_checksum              <= (others => '0');
                frame_crc                 <= (others => '1');
                gmii_tx_en                <= '0';
                gmii_txd                  <= x"00";
            else
                case state is
                    when IDLE =>
                        gmii_tx_en <= '0';
                        gmii_txd   <= x"00";
                        if udp_valid = '1' and udp_ready_i = '1' then
                            payload_latched       <= udp_payload;
                            checksum_word_counter  <= 0;
                            udp_sum                <= UDP_INITIAL_SUM;
                            frame_crc              <= (others => '1');
                            state                  <= CHECKSUM_PAYLOAD;
                        end if;

                    when CHECKSUM_PAYLOAD =>
                        gmii_tx_en <= '0';
                        gmii_txd   <= x"00";
                        has_low_byte :=
                            checksum_word_counter * 2 + 1 <
                            UDP_PAYLOAD_BYTE_COUNT;
                        payload_high := payload_latched'high -
                            checksum_word_counter * 16;
                        payload_word := (others => '0');
                        payload_word(15 downto 8) := unsigned(
                            payload_latched(
                                payload_high downto payload_high - 7));
                        if has_low_byte then
                            payload_word(7 downto 0) := unsigned(
                                payload_latched(
                                    payload_high - 8 downto
                                    payload_high - 15));
                        end if;
                        next_sum := checksum_add(
                            udp_sum, payload_word);
                        udp_sum <= next_sum;

                        if checksum_word_counter = PAYLOAD_WORD_COUNT - 1 then
                            udp_checksum     <= finish_udp_checksum(next_sum);
                            preamble_counter <= 0;
                            state            <= PREAMBLE;
                        else
                            checksum_word_counter <=
                                checksum_word_counter + 1;
                        end if;

                    when PREAMBLE =>
                        if clk_enable = '1' then
                            gmii_tx_en <= '1';
                            gmii_txd   <= x"55";
                            if preamble_counter = 6 then
                                preamble_counter <= 0;
                                state            <= SFD;
                            else
                                preamble_counter <= preamble_counter + 1;
                            end if;
                        end if;

                    when SFD =>
                        if clk_enable = '1' then
                            gmii_tx_en     <= '1';
                            gmii_txd       <= x"D5";
                            header_counter <= 0;
                            state          <= HEADER;
                        end if;

                    when HEADER =>
                        if clk_enable = '1' then
                            data_value := header_byte(
                                header_counter, udp_checksum);
                            gmii_tx_en <= '1';
                            gmii_txd   <= data_value;
                            frame_crc  <= crc32_next(frame_crc, data_value);

                            if header_counter =
                               PROTOCOL_HEADER_BYTES - 1 then
                                header_counter  <= 0;
                                payload_counter <= 0;
                                state           <= PAYLOAD;
                            else
                                header_counter <= header_counter + 1;
                            end if;
                        end if;

                    when PAYLOAD =>
                        if clk_enable = '1' then
                            payload_high := payload_latched'high -
                                payload_counter * 8;
                            data_value := payload_latched(
                                payload_high downto payload_high - 7);
                            gmii_tx_en <= '1';
                            gmii_txd   <= data_value;
                            frame_crc  <= crc32_next(frame_crc, data_value);

                            if payload_counter =
                               UDP_PAYLOAD_BYTE_COUNT - 1 then
                                payload_counter <= 0;
                                if PADDING_BYTE_COUNT = 0 then
                                    fcs_counter <= 0;
                                    state       <= FCS;
                                else
                                    padding_counter <= 0;
                                    state           <= PADDING;
                                end if;
                            else
                                payload_counter <= payload_counter + 1;
                            end if;
                        end if;

                    when PADDING =>
                        if clk_enable = '1' then
                            gmii_tx_en <= '1';
                            gmii_txd   <= x"00";
                            frame_crc  <= crc32_next(frame_crc, x"00");

                            if padding_counter = PADDING_LAST_INDEX then
                                padding_counter <= 0;
                                fcs_counter     <= 0;
                                state           <= FCS;
                            else
                                padding_counter <= padding_counter + 1;
                            end if;
                        end if;

                    when FCS =>
                        if clk_enable = '1' then
                            fcs_value  := not frame_crc;
                            gmii_tx_en <= '1';
                            case fcs_counter is
                                when 0 => gmii_txd <= fcs_value(7 downto 0);
                                when 1 => gmii_txd <= fcs_value(15 downto 8);
                                when 2 => gmii_txd <= fcs_value(23 downto 16);
                                when 3 => gmii_txd <= fcs_value(31 downto 24);
                            end case;

                            if fcs_counter = 3 then
                                fcs_counter <= 0;
                                ifg_counter <= 0;
                                state       <= INTER_FRAME_GAP;
                            else
                                fcs_counter <= fcs_counter + 1;
                            end if;
                        end if;

                    when INTER_FRAME_GAP =>
                        if clk_enable = '1' then
                            gmii_tx_en <= '0';
                            gmii_txd   <= x"00";
                            if ifg_counter = 11 then
                                ifg_counter <= 0;
                                frame_sent  <= '1';
                                state       <= IDLE;
                            else
                                ifg_counter <= ifg_counter + 1;
                            end if;
                        end if;
                end case;
            end if;
        end if;
    end process transmit;
end architecture rtl;
